apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: KEY
          value: $ADRIAN_TESTING
